apiVersion: v1
kind: Namespace
metadata:
  name: serverapp-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverapp
  namespace: serverapp-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      service: serverapp-svc
  template:
    metadata:
      labels:
        app: serverapp
        service: serverapp-svc
    spec:
      containers:
        - name: fleet-api
          image: patelakash50/serverapp:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: serverapp-svc
  namespace: serverapp-demo
  labels:
    app: serverapp
    service: serverapp-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    service: serverapp-svc